# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{classifier}
  s.version = "0.4.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.date = %q{2010-09-27}
  s.email = %q{jtoy@jtoy.net}
  s.executables = ["bayes.rb", "summarize.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    "LICENSE",
     "README",
     "Rakefile",
     "bin/bayes.rb",
     "bin/summarize.rb",
     "install.rb",
     "lib/classifier.rb",
     "lib/classifier/bayes.rb",
     "lib/classifier/extensions/string.rb",
     "lib/classifier/extensions/vector.rb",
     "lib/classifier/extensions/vector_serialize.rb",
     "lib/classifier/extensions/word_hash.rb",
     "lib/classifier/lsi.rb",
     "lib/classifier/lsi/content_node.rb",
     "lib/classifier/lsi/summary.rb",
     "lib/classifier/lsi/word_list.rb",
     "test/bayes/bayesian_test.rb",
     "test/extensions/word_hash_test.rb",
     "test/lsi/lsi_test.rb",
     "test/test_helper.rb"
  ]
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ruby Classifier - Bayesian and LSI classification library}
  s.test_files = [
    "test/bayes/bayesian_test.rb",
     "test/extensions/word_hash_test.rb",
     "test/lsi/lsi_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

